global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'user-service'
    static_configs:
      - targets: ['user:2112']

  - job_name: 'guild-service'
    static_configs:
      - targets: ['guild:2112']

  - job_name: 'message-service'
    static_configs:
      - targets: ['message:2112']

  - job_name: 'realtime-service'
    static_configs:
      - targets: ['realtime:2112']

  - job_name: 'media-service'
    static_configs:
      - targets: ['172.17.0.1:2112']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:2112']
