global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'user-service'
    dns_sd_configs:
      - names:
          - 'user'
        type: 'A'
        port: 2112

  - job_name: 'guild-service'
    static_configs:
      - targets: ['guild:2112']

  - job_name: 'message-service'
    static_configs:
      - targets: ['message:2112']

  - job_name: 'realtime-service'
    static_configs:
      - targets: ['realtime:2112']

  - job_name: 'media-service'
    static_configs:
      - targets: ['172.17.0.1:2112'] # dockerでhost networkを使っているためデフォルトゲートウェイのIPを指定

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:2112']

  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres-exporter:9187']
  
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
