services:
  web:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=${API_BASE_URL}
        - VITE_CLIENT_BASE_URL=${CLIENT_BASE_URL}
        - VITE_WS_BASE_URL=${WS_BASE_URL}
    ports:
      - "80:80"
    depends_on:
      - api-gateway

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: chat_app
      POSTGRES_USER: user
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  rustfs:
    image: rustfs/rustfs:latest
    ports:
      - "9001:9001"
    environment:
      - RUSTFS_VOLUMES=/data
      - RUSTFS_CONSOLE_ENABLE=true
      - RUSTFS_ACCESS_KEY=rustfsadmin
      - RUSTFS_SECRET_KEY=rustfsadmin
    volumes:
      - ./server/volumes/rustfs:/data

  user:
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: user
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres

  guild:
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: guild
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - USER_SERVICE_URL=user:50051
    depends_on:
      - postgres
      - user

  message:
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: message
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - USER_SERVICE_URL=user:50051
      - GUILD_SERVICE_URL=guild:50052
      - REDIS_ADDR=redis:6379
    depends_on:
      - postgres
      - user
      - guild
    
  realtime:
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: realtime
    environment:
      - REDIS_URL=redis:6379
      - REALTIME_SERVICE_PORT=50054
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "50054:50054"
    depends_on:
      - redis
      - user
      - message

  api-gateway:
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: api-gateway
    ports:
      - "8000:8000"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - USER_SERVICE_URL=user:50051
      - GUILD_SERVICE_URL=guild:50052
      - MESSAGE_SERVICE_URL=message:50053
    depends_on:
      - user
      - guild
      - message
      - realtime

volumes:
  postgres_data:
