apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: chat-app
  sources:
    - chart: loki
      repoURL: https://grafana.github.io/helm-charts
      targetRevision: 6.49.0
      helm:
        valueFiles:
          - $values/k8s/argocd/values/loki.yaml
    - repoURL: https://github.com/nomanoma121/chat-app
      targetRevision: feat/introduce-k8s
      ref: values
      path: k8s/argocd/values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
