apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: chat-app
  sources:
    - chart: minio
      repoURL: https://charts.min.io/
      targetRevision: 5.0.0
      helm:
        valueFiles:
          - $values/minio.yaml
    - repoURL: https://github.com/nomanoma121/chat-app
      targetRevision: main
      ref: values
      path: k8s/argocd/values
  destination:
    server: https://kubernetes.default.svc
    namespace: storage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
