apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
spec:
  project: chat-app
  sources:
    - chart: postgresql
      repoURL: https://charts.bitnami.com/bitnami
      targetRevision: 18.1.14
      helm:
        valueFiles:
          - $values/k8s/argocd/values/postgres.yaml
    - repoURL: https://github.com/nomanoma121/chat-app
      targetRevision: feat/introduce-k8s
      ref: values
      path: k8s/argocd/values
  destination:
    server: https://kubernetes.default.svc
    namespace: database
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
