apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
spec:
  project: chat-app
  sources:
    - chart: tempo
      repoURL: https://grafana.github.io/helm-charts
      targetRevision: 1.0.0
      helm:
        valueFiles:
          - $values/tempo.yaml
    - repoURL: https://github.com/nomanoma121/chat-app
      targetRevision: main
      ref: values
      path: k8s/argocd/values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
