apiVersion: apps/v1
kind: Deployment
metadata:
  name: guild
  labels:
    app: guild
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guild
  template:
    metadata:
      labels:
        app: guild
    spec:
      containers:
        - name: guild
          image: chat-app-guild:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 50052
              name: grpc
            - containerPort: 6060
              name: pprof
            - containerPort: 2112
              name: metrics
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: guild
spec:
  selector:
    app: guild
  ports:
    - name: grpc
      protocol: TCP
      port: 50052
      targetPort: 50052
    - name: pprof
      protocol: TCP
      port: 6060
      targetPort: 6060
    - name: metrics
      protocol: TCP
      port: 2112
      targetPort: 2112
