apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gateway.yaml
  - guild.yaml
  - media.yaml
  - message.yaml
  - user.yaml
  - realtime.yaml

configMapGenerator:
  - name: app-config
    literals:
      - USER_SERVICE_URL=user:50051
      - GUILD_SERVICE_URL=guild:50052
      - MESSAGE_SERVICE_URL=message:50053
      - REALTIME_SERVICE_URL=realtime:50054
      - MEDIA_SERVICE_URL=media:50055
      - REDIS_ADDR=redis-master.database:6379
      - OTEL_EXPORTER_OTLP_ENDPOINT=alloy.monitoring:4317

generatorOptions:
  disableNameSuffixHash: true
