name: golangci-lint
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  go-lint:
    name: go-lint(${{ matrix.path }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - ./server/services/message
          - ./server/services/realtime
          - ./server/services/guild
          - ./server/services/user
          - ./server/services/media
          - ./server/services/api-gateway
          - ./server/shared
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: 1.25.1
      - name: golangci-lint install
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.5
          working-directory: ${{ matrix.path }}
          
  client-lint:
    name: client-lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v2
        with:
          version: 10.15.0
      - name: Install dependencies
        run: pnpm install
      - name: Run Biome Check
        run: pnpm biome lint ./app
